### ISSUE TITLE
Aurelia/Core-JS dependencies need updating

### ISSUE THREAD

**Issue by chrismbeckett** [Vheissu/Aurelia-Configuration#10]
After upgrading my project to Aurelia Beta 1 and bundling, I am seeing duplicates and old versions included in the bundle in my ``config.js`` that seem to be related to this package. Aurelia has also updated their Core-JS dependency to 1.2.6 so I am seeing a duplicate of that.

Here are the specific packages being added to the bundler by using your package right now. You can check this in the ``config.js`` under ``bundles``:

```js
{
      "github:aurelia/dependency-injection@0.9.2",
      "github:aurelia/dependency-injection@0.9.2/aurelia-dependency-injection",
      "github:aurelia/event-aggregator@0.7.0",
      "github:aurelia/event-aggregator@0.7.0/aurelia-event-aggregator",
      "github:aurelia/http-client@0.10.3",
      "github:aurelia/http-client@0.10.3/aurelia-http-client",
      "github:aurelia/logging@0.6.4",
      "github:aurelia/logging@0.6.4/aurelia-logging",
      "github:aurelia/metadata@0.7.3",
      "github:aurelia/metadata@0.7.3/aurelia-metadata",
      "github:aurelia/path@0.8.1",
      "github:aurelia/path@0.8.1/aurelia-path"
}
```

**Comment by Vheissu** [comment]
Addressed in release 1.0.4
