### ISSUE TITLE
Configuration file could not be found: config/config.json

### ISSUE THREAD

**Issue by Kizmar** [Vheissu/aurelia-configuration#100]
I’m using the `dotnet new aurelia` template and can’t get this plugin to work. I'm guessing it has something to do with it being pulled in as a module instead of a physical file in the `dist/` folder? Here's what I have set up:

Added this to `webpack.config.js`:
```
module: {
   rules: [
      { test: /\.json$/, use: 'json-loader' }
      ...         
```
My `boot.ts` (main.ts): _extra code omitted for simplicity_
```
import { Aurelia, PLATFORM } from 'aurelia-framework';
...
import 'config/config.json';
...
export async function configure(aurelia: Aurelia) {
    aurelia.use
        .standardConfiguration()
        ...
        .plugin(PLATFORM.moduleName('aurelia-configuration'));
    ...
}
```
I can tell webpack is adding the `config.json` file contents as a module to `dist/app.js`, but I’m unable to get aurelia-configuration pointed at it. I keep getting “Uncaught (in promise) Configuration file could not be found: config/config.json”.

Directory structure:
_ClientApp/boot.ts
ClientApp/config/config.json_

**Comment by LazerFX** [comment]
How did you resolve this issue?  I'm having the same problem - importing via webpack and not successful in viewing.  Please advise!  (And, if you resolve a problem, don't just close the question!!!)

**Comment by LazerFX** [comment]
I've resorted to using `copy-webpack-plugin`.

For those who also run into this, while I'm sure there's a better answer, the following changes to `webpack.config.js` will work:

`...
const CopyWebpackPlugin = require('copy-webpack-plugin')
...
plugins: [
    new CopyWebpackPlugin([{ from: 'ClientApp/config/config.json', to: './../config/config.json' }],
    { copyUnmodified: true }),
....`

Note: the `./../config` - it does not like loading from `/dist/config/config.json`.
