### ISSUE TITLE
Typings File Using Aurelia Skeleton with Jspm

### ISSUE THREAD

**Issue by wpearson4** [Vheissu/aurelia-configuration#104]
I am currently having to reference the typings as follows "import {AureliaConfiguration} from '../jspm_packages/github/vheissu/aurelia-configuration@1.0.17'".  Am I missing something or is this the only way I can import AureliaConfiguration with TypeScript

**Comment by Vheissu** [comment]
JSPM is one of those things that has had a checkered history with typings and TypeScript support. I am looking at better typing support in the next release.
