### ISSUE TITLE
bundle application.json or ability to use json object only

### ISSUE THREAD

**Issue by doktordirk** [Vheissu/Aurelia-Configuration#11]
making always an extra http request for the application.json on production seems unneeded. i'd like an option either to bundle the json somehow, or to removing the autoloading and using setAll myself with an json object i have in eg main.js without the then unneeded application.json loading

**Comment by Vheissu** [comment]
There will be an option to both use server-side loaded JSON, client-side and bundled options as well. This will be in the next version.

**Comment by doktordirk** [comment]
sounds great. tx

**Comment by Vheissu** [comment]
There is a merge function in release 1.0.4 that should support working with objects.
