### ISSUE TITLE
update-dependencies fork is not current

### ISSUE THREAD

**Issue by jsobell** [Vheissu/Aurelia-Configuration#12]
The current head doesn't refer to the beta version of Aurelia on npm.
Current workaround requires
jspm install aurelia-configuration=github:derekpitt/Aurelia-Configuration@update-dependencies
(fork by derekpitt)

**Comment by Vheissu** [comment]
Yes, you are correct. My apologies, I have been quite busy and not had enough time to update things with Christmas and all. Will push out some fixes shortly.

**Comment by Vheissu** [comment]
Addressed in release 1.0.4
