### ISSUE TITLE
How do I use it with aurelia-auth?

### ISSUE THREAD

**Issue by afm-sayem** [Vheissu/Aurelia-Configuration#16]
All the examples show how to use aurelia-configuration in view-models. How do I use aurelia-config to configure a plugin(like aurelia-auth)?

**Comment by Vheissu** [comment]
This is a good question and once the newer release is pushed out, there should be more examples how how you would use this with other plugins like Aurelia Auth.

**Comment by riddla** [comment]
I recently had a similar use case and came up with the following solution:

```javascript
import {Configure} from "aurelia-configuration";
// [...]
aurelia.use
        .standardConfiguration()
        .plugin('aurelia-i18n', (instance) => {
                let configInstance = aurelia.container.get(Configure);
                let apiEndpoint = configInstance.get('api.endpoint');
// [...]
```
