### ISSUE TITLE
Setting the environment

### ISSUE THREAD

**Issue by wshayes** [Vheissu/Aurelia-Configuration#2]
Nice plugin!  I'm trying to figure out how to deploy with different environments (e.g. Dev, Staging, Prod) without changing my Aurelia configuration file.  What would you recommend?  I was thinking about using document.location.host to set my environment.  Is there a better way?

**Comment by Vheissu** [comment]
Ah, yes. Good question. The solution you posed would definitely work. It is a little late for me, so I can't really think of anything at the moment. Would there be value in having this kind of smart environment checking built into the plugin itself?

**Comment by wshayes** [comment]
It would be nice to have a standard approach for this supported in the plugin.  I was hoping you could either document a good pattern for this in your Readme or build it into the module.  Catch you on the other side of your night :)

**Comment by Vheissu** [comment]
Absolutely agree. I have started on an idea I have for configuring dynamic environments the plugin will pick up. In the master branch I've started a little WIP. Essentially the idea I have is a method called setEnvironments and during the config phase you pass in an array of environments and hosts to map. Then the plugin just checks. I've updated a README with what the syntax will look like (in the master branch).

**Comment by wshayes** [comment]
That looks really simple and powerful.  This plugin was already immediately added to my project when I saw it.  That was the last bit I needed.  Thank you!

**Comment by Vheissu** [comment]
No problem @wshayes 

I have just released a new version 1.0.3 which has dynamic environments added in. You can either have the concept of dynamic environments using the hostname or do it the old fashioned way: https://github.com/Vheissu/Aurelia-Configuration/releases/tag/1.0.3
