### ISSUE TITLE
get() returns the parent object instead of a primitive value 

### ISSUE THREAD

**Issue by eliranmal** [Vheissu/aurelia-configuration#23]
### description

when retrieving config values via the `get()` function, the returned value is the object wrapping the value, and not the value itself.
### steps to reproduce
1. create a config file with the default configuration (don't change the file path or name), with a nested object, e.g.:
   
   ```
   {
       "exit": {
           "timeout": {
               "duration": 2000
           }
       }
   }
   ```
2. inject the config service into a view
3. after the app bootstrap, and the view is attached, attempt to retrieve a nested value, e.g.:
   
   ```
   let duration = this.config.get('exit.timeout.duration');
   ```
### expected result

the retrieved value reference (`duration`) should have the config primitive value, e.g. `2000`.
### actual result

the retrieved value reference holds the wrapping object instead, e.g. `{ "duration": 2000 }`.
### environment details
- **jspm version:** 1.0.4
- **OS:** linux ubuntu 15.10 64-bit
- **browser:** chromium 48.0.2564.116

**Comment by eliranmal** [comment]
**workaround:** retrieve one level up, and get the value from the returned object's own properties:

    let duration = this.config.get('exit.timeout').duration;

**Comment by Vheissu** [comment]
This is definitely unexpected behaviour. I'll get a fix in for this.

**Comment by maroy1986** [comment]
Any update on this? I've hit the same "issue" here with the latest version.

**Comment by don-bluelinegrid** [comment]
+1

Same here, still.  This is very unexpected behavior, because these two calls return the exact same data object:

`this.appConfig.get('server.case.tags')`
`this.appConfig.get('server.case')`

It seems as though there may be some hard-coded assumption that only two levels of key nesting will be used?

Thanks,
Don

**Comment by maroy1986** [comment]
I had a look at the code, I've found where this is happening, as you said @don-bluelinegrid , it is hardcoded to 2 levels. I might take the take to try to fix it since author doesn't seen this for months, shouldn't be very hard.

**Comment by don-bluelinegrid** [comment]
@Vheissu 

This is now a well-documented bug, not operating as designed or as documented.
What is the plan?

Thanks,
Don
