### ISSUE TITLE
Error: loader must implement loadText(url)

### ISSUE THREAD

**Issue by weagle08** [Vheissu/Aurelia-Configuration#29]
i'm just trying to load the 'aurelia-configuration' plugin and get the following error:

*loader must implement loadText(url)*

```javascript
export function configure(aurelia) {
    aurelia.use
        .standardConfiguration()
        .developmentLogging()
        .plugin('aurelia-configuration');

    aurelia.start().then(a => a.setRoot('pages/app', document.body));
}
```

![image](https://cloud.githubusercontent.com/assets/7888478/14057528/baba468a-f2d0-11e5-887a-257dae7a313f.png)

**Comment by weagle08** [comment]
updated to latest Aurelia and this issue went away, but I noticed that the default path for the config file is now 'config/config.json', this does not seem to be documented anywhere. also how do i specify my own path to the config file when loading this module as an aurelia plugin?

**Comment by weagle08** [comment]
updated to latest aurelia and it works.. how do you specify a custom config path and still use this as a plugin?

**Comment by eliranmal** [comment]
you mean like this?

```
// ...
.plugin('aurelia-configuration', config => {
            config.setDirectory('config-files');
            config.setConfig('mycoolconfig.json');
        });

```
see [changing directory and/or file name][1] in this repo's README.


[1]: https://github.com/Vheissu/Aurelia-Configuration#changing-directory-andor-filename
