### ISSUE TITLE
Merging configuration

### ISSUE THREAD

**Issue by vcardins** [Vheissu/Aurelia-Configuration#3]
I'd like to be able to merge the configuration object instead of setting property by property. e.g: getting partial config json from server and merging to the local.

**Comment by paulvanbladel** [comment]
Very very nice plugin with a very neat design. Thanks a lot.

I struggled with that config merge issue as well, while working on aurelia-auth. There the situation is quite similar. Aurelia-auth needs a bunch of settings, which are mainly fixed except a few, the clientIds for the different auth providers.
At first glance Object.assign could do the job, but unfortunately it doesn't work in a recursive manner, which is needed when the setting file contains sub arrays and object.
Therefor, I simply 'stole' the angular.merge method which you can find in aurelia-auth (transformed to eS6 of course)

https://github.com/paulvanbladel/aurelia-auth/blob/master/src/authUtils.js#L105-108
I think Lodash has similar functionality.

Cheers
paul.

**Comment by Vheissu** [comment]
Being able to merge in from a server-side endpoint is a good idea. I did have it scribbled down somewhere and thanks to Paul's reference link above for a merge function, it shouldn't be too much trouble.

Are there any preferences for how this would ideally work?

**Comment by Vheissu** [comment]
There is a merge function in release 1.0.4 which allows you to merge in configuration options with pre-existing configuration.
