### ISSUE TITLE
Unhandled promise rejection Error: Loader must implement loadText(url)

### ISSUE THREAD

**Issue by spapaseit** [Vheissu/Aurelia-Configuration#31]
I've just installed aurelia-configuration from jspm on an Aurelia application based on the navigation-skeleton. I've set up some basic config.json and initialized the plugin on main.js, but now the application won't load up anymore, throwing the following error

`Unhandled promise rejection Error: Loader must implement loadText(url)`

It seems like aurelia-configuration is using the [aurelia-loader abstract module](https://github.com/aurelia/loader) instead of it's [default implementation](https://github.com/aurelia/loader-default).

Am I missing something or has something changed in the dependencies?

I have still not upgraded my aurelia app to use Babel 6 by the way, in case that is relevant.

**Comment by valgeirb** [comment]
+1

**Comment by iainduff** [comment]
+1

**Comment by iainduff** [comment]
I'm a noob so this is probably the wrong way to go about it but just noticed that in config.js of your project if you change the following it will work correctly. 

`"aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1.1.1"`
to
`"aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1.2.0"`

It gets you up and running until a fix is in place as obviously running jspm install again will overwrite it.

**Comment by meash-nrel** [comment]
Thanks for the quick fix.  Hopefully a new release is wrapped up soon.

**Comment by niedarek** [comment]
I've just installed version 1.0.6. Problem still exist.

**Comment by Vheissu** [comment]
Getting out a new release ASAP which fixes this. Sorry. I am sick so a little slower.
