### ISSUE TITLE
config files and git and security.

### ISSUE THREAD

**Issue by paulvanbladel** [Vheissu/aurelia-configuration#4]
Although security is less of an issue for client side config files, it still matters.
Especially in enterprise context, sometimes production config files are only merged-in during deployment by the operations teams and devs even never see the production config files. So, ... YMMV.

As far as I can see aurelia-configuration has all is environments in one file. Could be maybe an interesting option to allow multiple files. Should be doable with a decent merge function ? :)

Thanks for the great plugin.

**Comment by Vheissu** [comment]
Great ideas Paul. Did you have any ideas as to how this might look? Do you think it is a good idea to perhaps break out environment functionality into separate files and get rid of the current approach of all environments in the one file, or keep both approaches and allow the user to choose?

Definitely agree that committing environment values for all environments is not how it would be in deploy-to-production scenarios (especially within larger companies).

**Comment by paulvanbladel** [comment]
Hi Dwayne ,

Ideally, a combination of both would be preferable since often people have only one environment or might have reasons why one file is sufficient.

I have done something with environment dependent config files (but not as sophisticated as what you are already doing !) in aurelia-auth-sample.but server side in NodeJs:

https://github.com/paulvanbladel/aurelia-auth-sample/blob/master/server/config/index.js

**Comment by Vheissu** [comment]
No worries Paul. I have started exploring the concept and have the merging and whatnot working. I think it might be a partially breaking change, however if you only have the one file, then the default settings will still work as expected. I am thinking of something like this:

setEnvironments({
    development: {
        json: 'configfordevelopment.json',
        hostnames: '*' // Wildcard * means any host
    },
    production: {
        json: 'production/api/config/v2',
        hostnames: ['example.com', 'prod.example.com']
    }
});

The general idea here is that if you don't specify a .json file, it assumes an endpoint where your settings are pulled in from some kind of API. What do you think? Am I on the right track here?

**Comment by paulvanbladel** [comment]
Definitely, sounds like a great design.
Thanks a lot.

**Comment by adriatic** [comment]
Paul is of course right - from a viewpoint of any distributed application development (discipline very different from application front end development **in isolation** from other application components), having anything that can be hacked and then compromise the whole application is unacceptable. 

This is of course the reason all security vendors would configure the app on the server side (as Paul mentioned above) -- **and** in most tutorials provide scripts that set all configuration parameters in the app ENVIRONMENT. 

Such approach is bothersome for the developers (I always swear when I need to do that), so Dwayne's configuration plugin is god sent, provided that it detects the environment automatically acts accordingly - configures the app in development mode.

We Aurelians wannabes should all think a lot more about the whole distributed system than we currently do trying to really assimilate Aurelia.

**Comment by jonathaneckman** [comment]
I am looking for a similar solution to the same problem. Our Aurelia app runs within a .NET Core web application. Our environment variables are stored on the server in our appsettings.json. Currently, these variables are handed off to Aurelia as globals injected on the server:

    <script type="text/javascript">
        var API_URL = "@UrlSettings.Value.Api";
        var AUTH_URL = "@UrlSettings.Value.Auth";
    </script>

This feels dirty. What I'm looking for is a way to pass these right into the aurelia-app element. For example, this would be in index.cshtml:

     <div aurelia-app="boot" config.bind="{
          apiUrl: "@UrlSettings.Value.Api",
          authUrl: "@UrlSettings.Value.Auth"
     }">Loading...</div>

These could then be received while the app is booting and aurelia-configuration would take it from there. My boot.ts would look like this:

    export function configure(aurelia) {
      
      @bindable
      config = {};

      aurelia.use
          .standardConfiguration()
          .developmentLogging()
          .plugin('aurelia-configuration', config => {
              config.merge(this.config); 
          });

      aurelia.start().then(a => a.setRoot());
    }

I know my use of `bindable` isnt a very good example, but hopefully it illustrates the behavior I'm after.
