### ISSUE TITLE
error loading deep-extend in 1.0.6

### ISSUE THREAD

**Issue by meash-nrel** [Vheissu/Aurelia-Configuration#41]
just installed new release 1.0.6

```
Uncaught (in promise) Error: XHR error (404 Not Found) loading http://localhost:9000/dist/deep-extend.js(…)
```

deep-extend is in package.json in dependencies, not jspm dependencies...

circumvented the error for now by manually installing it via `jspm install npm:deep-extend`

**Comment by Vheissu** [comment]
This is due to a dependency being fixed for Webpack but being removed from Jspm. This will be fixed next update. In the interim `jspm install npm:deep-extend` will fix the issue until next release.
