### ISSUE TITLE
Getting a 404 loading aurelia-configuration@1.0.7.js

### ISSUE THREAD

**Issue by alsoicode** [Vheissu/Aurelia-Configuration#43]
Hello. I'm getting a 404 from aurelia-configuration on a fresh install:

http://localhost:9000/jspm_packages/github/vheissu/aurelia-configuration@1.0.7.js -> 404

My config file is at /config/config.json which should be the default.

My `main.js` is as follows:

```
export function configure(aurelia) {
  aurelia.use
    .standardConfiguration()
    .developmentLogging()
    .plugin('aurelia-configuration', config => {
      config.setCascadeMode(false);
      config.setEnvironments({
        development: ['localhost', '192.168.*.*'],
        production: ['brandonftaylor.com', 'www.brandonftaylor.com']
      });
    })
    .plugin('aurelia-validation');
```

The stack trace from Chrome Developer Tools:

```
system.js:4 Uncaught (in promise) Error: XHR error (404 Not Found) loading http://localhost:9000/jspm_packages/github/vheissu/aurelia-configuration@1.0.7.js
	Error loading http://localhost:9000/jspm_packages/github/vheissu/aurelia-configuration@1.0.7.js
    at o (http://localhost:9000/jspm_packages/system.js:4:12694)
    at XMLHttpRequest.s.onreadystatechange (http://localhost:9000/jspm_packages/system.js:4:13219)t @ system.src.js:4597g @ system.src.js:4597(anonymous function) @ system.src.js:4597
```

Thoughts?

**Comment by raskolnikoov** [comment]
I also have this problem. Any solution for this please?

**Comment by snortblt** [comment]
+1

**Comment by djthread** [comment]
Me, too.

**Comment by komenixx** [comment]
+1

**Comment by SamuelCaudenberg** [comment]
I had the same issue

**Comment by Vheissu** [comment]
I am looking into this. It is a path issue I am going to solve.

**Comment by wshayes** [comment]
Any progress on this?  Trying to figure out if I need to remove this plugin or try to figure out how to fix it.  My app is currently broken.

**Comment by SamuelCaudenberg** [comment]
Just write this in your package.json file:
"aurelia-configuration": "github:vheissu/aurelia-configuration@1.0.4",

Place it under 
"jspm": {
    "dependencies": {
}

It basically makes sure you use an older version and it will not update the plugin to a newer one

**Comment by Vheissu** [comment]
As @SamuelCaudenberg points out the older version should suffice for the moment. I am currently working on a more streamlined version that fixes the issues. Alternatives to this plugin for more simple needs are simply creating a JSON file and then importing it like a normal file. This means you lose the deep extend, environment merging, etc though. Working as fast as I can, sorry guys.

**Comment by wshayes** [comment]
Thanks Samuel - I tried the 1.0.5 - didn't go back far enough.  Dwayne - I appreciate the plugin - nicely done and available for free.  I'm not trying to be pushy - just trying to figure out which way to jump for a near term delivery.  I also hate to take your time away from the book which has saved me a LOT of time and pain.

**Comment by Vheissu** [comment]
@wshayes Haha not pushy at all. I do aim to get on this ASAP, possibly today actually. I want to change how the files are loaded, well abstract it out because now we have System.js and Webpack users to contend with, which complicates things a little bit from a loading perspective.

**Comment by date13** [comment]
how to resolve this problem,who know

**Comment by wshayes** [comment]
Use the 1.0.4 version —>  jspm install aurelia-configuration@1.0.4  which works with jspm

**Comment by alsoicode** [comment]
Version 1.0.6 is working for me.

**Comment by Vheissu** [comment]
Does the latest release fix this for everyone?

**Comment by izderadicka** [comment]
Actually I still have this issue - installed plugin an hour ago:
```
Error: XHR error (404 Not Found) loading http://localhost:9000/jspm_packages/github/vheissu/aurelia-configuration@1.0.8.js
	Error loading http://localhost:9000/jspm_packages/github/vheissu/aurelia-configuration@1.0.8.js
```

**Comment by chrisjshelby** [comment]
nope still getting the error

**Comment by crabulik** [comment]
yeap, the same error.

**Comment by fragsalat** [comment]
:+1: 
Even if I add the required file manually I get error's about the dependencies of Container and after that some markup creation error.
The Container has the aurelia-loader.Loader but only DefaultLoader is there.

**Comment by dgelvin** [comment]
Experiencing this error with 1.0.8, override fix above did not resolve the issue for me.

**Comment by SteveDuitsman** [comment]
I'm also experiencing this with a fresh install of 1.0.8. No warnings on the install either.

Thanks for looking into this.

**Comment by pszybiak** [comment]
Version 1.0.8 works fine, but when you install it manually, not by jspm install (look at #47)

**Comment by emgiezet** [comment]
+1

**Comment by Vheissu** [comment]
This should be fixed latest release 1.0.9

**Comment by alsoicode** [comment]
w00t. Can't wait to try 1.0.9 out.

**Comment by bdatta1981** [comment]
The issue still persists in 1.0.9.

**Comment by JeroenVinke** [comment]
For anyone interested in a fix: https://github.com/Vheissu/Aurelia-Configuration/pull/50#issue-162105753

**Comment by stevies** [comment]
Getting the same issue with aurelia-configuration 1.0.13 - using webpack (from the skeleton es6 webpack)
```
/config/config.json 404 (Not Found)
```
