### ISSUE TITLE
use aurelia-loader instead of aurelia-loader-default

### ISSUE THREAD

**Issue by Scapal** [Vheissu/Aurelia-Configuration#44]
In order to work correctly with both jspm and webpack, could you use `aurelia-loader` instead of `aurelia-loader-default`

**Comment by m-andrew-albright** [comment]
I want to use this plug-in in my application, but can't due to this issue (we are using Webpack and ES2015).  Is there a work-around in the meantime of implementing this fix?

**Comment by raiseandfall** [comment]
Hey guys,
In the meantime you can use [this fork](https://github.com/learningmachine/Aurelia-Configuration)

**Comment by m-andrew-albright** [comment]
@raiseandfall I'm somewhat new to a lot of the tooling in front end development.  How would I install and use that fork via npm?

**Comment by raiseandfall** [comment]
@m-andrew-albright sure, makes more sense if I paste the dependency line in package.json:
```json
"dependencies": { 
  "aurelia-configuration": "https://github.com/learningmachine/Aurelia-Configuration/tarball/1.0.7"
}
```

**Comment by m-andrew-albright** [comment]
@raiseandfall  When I try to run after adding this dependency, I'm getting this error:

Uncaught Error: Cannot find module "aurelia-http-client" -  aurelia-configuration/dist/commonjs/configure.js:13

I currently am only using the aurelia-fetch-client in my application; does this have a dependency on aurelia-http-client?  If so, what is it using that for?  Can I circumvent this somehow?

**Comment by raiseandfall** [comment]
@m-andrew-albright I don't think that's related to this dependency (I don't have the issue). Did you try installing it?

**Comment by Vheissu** [comment]
This is fixed in the latest release. Sorry this took so long.
