### ISSUE TITLE
jspm install download version 1.0.7 as 1.0.8

### ISSUE THREAD

**Issue by pszybiak** [Vheissu/Aurelia-Configuration#47]
"dist" catalog isn't updated in 1.0.8 release.
When I run `jspm install aurelia-configuration` binaries are old.

**Comment by emgiezet** [comment]
+1

**Comment by emgiezet** [comment]
you can quick fix it by:

```
jspm install aurelia-configuration -o '{main: "index.js"}'
```

**Comment by Vheissu** [comment]
Sorry about this guys. This should now be fixed in the latest release. I refactored the tooling/dts generation stuff.
