### ISSUE TITLE
Not being injected when using TypeScript @autoinject decorator

### ISSUE THREAD

**Issue by vcardins** [Vheissu/Aurelia-Configuration#5]

**Comment by Vheissu** [comment]
Thanks for reporting @vcardins I will be looking into this hopefully today. I am not a TypeScript user, so I'll have to get an environment setup.

**Comment by vcardins** [comment]
Thank you, Vheissu ! Very useful piece ;) Looking forward to hearing from you !

**Comment by Vheissu** [comment]
The addition of TypeScript definition files and a proper package in release 1.0.4 should address this issue.
