### ISSUE TITLE
Typescript definition error

### ISSUE THREAD

**Issue by nkassis** [Vheissu/Aurelia-Configuration#51]
I've been trying to use the definitions in dist but i'm getting the following error while building: 

> custom_typings\aurelia-configuration.d.ts(211,1): error TS1128: Declaration or statement expected.
custom_typings\aurelia-configuration.d.ts(211,16): error TS1005: ';' expected.

Typescript version "typescript@^1.9.0-dev.20160622-1.0",

**Comment by Vheissu** [comment]
Typings should be fixed in latest version 1.0.11
