### ISSUE TITLE
typings d.ts file discoverable and installable by "typings"?

### ISSUE THREAD

**Issue by dkent600** [Vheissu/Aurelia-Configuration#52]
It would be nice to have typings (.d.ts) published so that it is discoverable and installable by "typings".

**Comment by art0rz** [comment]
It's installable by running

`typings install github:vheissu/aurelia-configuration`

However, I'm getting a syntax error on this line https://github.com/Vheissu/Aurelia-Configuration/blob/master/dist/aurelia-configuration.d.ts#L211

**Comment by dkent600** [comment]
All of the following commands return "No results found for search".  This should not be the case:

typings search github:vheissu/aurelia-configuration
typings search vheissu/aurelia-configuration
typings search aurelia-configuration

**Comment by Vheissu** [comment]
The latest version of the plugin 1.0.11 has the typings shipping with the plugin. Module resolution type of Node should see them.

**Comment by dkent600** [comment]
The following commands still return "No results found for search".:

typings search github:vheissu/aurelia-configuration
 typings search vheissu/aurelia-configuration
 typings search aurelia-configuration

**Comment by htxryan** [comment]
This issue should be reopened, as typings installation does not work with the following command:

typings install github:vheissu/aurelia-configuration
