### ISSUE TITLE
Configure isn't loading config.json

### ISSUE THREAD

**Issue by dkent600** [Vheissu/Aurelia-Configuration#54]
I'm calling this:  `.plugin('aurelia-configuration')`

but `Configure.loadConfig` is never being invoked.  The docs don't state that this must be called manually.

(I'm using JSPM/SystemJs)

**Comment by dkent600** [comment]
I also note that in the following code, the callback is never invoked:

```
aurelia.use
.plugin('aurelia-configuration', (config: any) => {
            config.setEnvironment(environment); // environment is set in _AureliaScriptsPartial.cshtml
        })
```

**Comment by dkent600** [comment]
These are turning out to be killers for me.  Is this package still being maintained?

**Comment by Vheissu** [comment]
@dkent600 Package is still being maintained, I just have a lot going on now with work and other aspects of life. I am sorry, I am getting to this. This is fixed, I just need to release. Lots of planned changes coming.

**Comment by dkent600** [comment]
@Vheissu Cool, thanks for the reply, I'm looking forward to the next release!  :-)

**Comment by Vheissu** [comment]
Try the latest release now @dkent600

**Comment by meash-nrel** [comment]
plugin callback is not called in latest 1.0.12 and Aurelia 1.0


```
aurelia.use
.plugin('aurelia-configuration', (config) => {
           console.log("Hit this?");
        })
```

never hits the console.log ...

**Comment by dkent600** [comment]
This appears to be fixed.  I'm using 1.0.14.
