### ISSUE TITLE
configure.d.ts should not cause compile error ("readonly")

### ISSUE THREAD

**Issue by dkent600** [Vheissu/Aurelia-Configuration#56]
Ther presence of "readonly" in configure.d.ts causes tsc compile to fail with:

`error TS1005: '=' expected`

**Comment by Vheissu** [comment]
In what kind of application are you seeing this? The configure.d.ts file is automatically generated. I wonder if this is actually a code error.

**Comment by dkent600** [comment]
I'm seeing this when running tsc to transpile my typescript.

**Comment by Vheissu** [comment]
This is fixed in release 1.0.13

**Comment by dkent600** [comment]
Do you mean 1.8.13 perchance?
