### ISSUE TITLE
Cannot find module './config/config.json'

### ISSUE THREAD

**Issue by Vaccano** [Vheissu/Aurelia-Configuration#59]
I have followed the steps for using this with webpack.  

When I do, I get the following error:

>Error: Cannot find module './config/config.json'.

This prints in the console right after `DEBUG [aurelia] Loading plugin aurelia-configuration.`

I have double checked and the file is in `dist/config/config.json`.  

Is there something I am missing?

**Comment by StephenCleary** [comment]
We are having this issue as well, using webpack (with `aurelia-webpack-plugin`).

Downgrading to `1.0.3` (using HTTP instead of the loader) is a workaround until this issue is resolved.

**Comment by molnara** [comment]
Same issue, but after downgrade I get error:
#63

**Comment by Vheissu** [comment]
This should be fixed in the latest release 1.0.13

**Comment by stevies** [comment]
1.0.13 still gives me this error.  Using webpack.

**Comment by originAsad** [comment]
You were Getting this Error due to the Wrong path of model in Var or Const i have get the same issue and i just Correct the path TRY TO CORRECT THE PATH OF MODEL IN WHICH YOU HAVE RECENTLY CALLED it fixed by issue after two days of struggle
