### ISSUE TITLE
Plugin initialization bug

### ISSUE THREAD

**Issue by tszarzynski** [Vheissu/Aurelia-Configuration#61]
Someone already reported that issue, but closed it after reverting to previous version of the plugin.

When I try to use the plugin i'm getting this:

`Unhandled rejection Error: (SystemJS) Error: key/value cannot be null or undefined. Are you trying to inject/register something that doesn't exist with DI?`

From my observations it looks like `configure` method is not being called and plugin is not initialised properly. My code is the same as README samples. Using version 1.0.12.

I can also confirm that version 1.0.11 seems to work fine.

**Comment by micro-jumbo** [comment]
I got the same message after upgrading my aurelia dependencies from 1.0.0rc to 1.0.0
1.0.11 works fine

**Comment by ardean** [comment]
+1 same here

**Comment by Freshcutdevelopment** [comment]
Yeah I've reverted to 1.0.11 as well.

**Comment by Vheissu** [comment]
This is fixed in release 1.0.13. Thanks and sorry guys.

**Comment by htxryan** [comment]
This is still broken for me in 1.0.13
