### ISSUE TITLE
Cannot read property '__useDefault' of undefined

### ISSUE THREAD

**Issue by amitfou** [Vheissu/Aurelia-Configuration#65]
Hi,
I am having a typescript based aurelia cli project. The issue is when I try to load the Aurelia-Configuration plugin I get the following error

>DEBUG [aurelia] Loading plugin aurelia-configuration.
>vendor-bundle.js:21077 Uncaught TypeError: Cannot read property '__useDefault' of undefined

Not sure if I am doing anything wrong as I do not see any error on the cli console. I have added the dependency of aurelia-configuration in aurelia.json

**Comment by heiko5** [comment]
I had some problems aswell. I think this one was gone, after i put the [deep-extend.js](https://github.com/unclechu/node-deep-extend/blob/master/lib/deep-extend.js) in my src folder. You also might need to go into your aurelia.json, and set stub-property in `build.loader[0].plugins` to false.
And last but not least, you need to add aurelia-configuration to your dependencies in your aurelia.json like so`
```
{
      "name": "aurelia-configuration",
      "path": "../node_modules/aurelia-configuration/dist/commonjs",
      "main": "index"
}
```

**Comment by Vheissu** [comment]
Thank you for the above @heiko5 this should resolve the issue people are having. The CLI being AMD based means sometimes you need to manually supply a different route.

**Comment by TheNewFM** [comment]
@heiko5 when you run into "cannot find" with aurelia-cli, you don't need to copy the file to your src folder. You just need to add another bundle reference for that file. In this case it is a dependency of aurelia-configuration so it is already installed. This should suffice in your aurelia.json:

```
{
  "name": "aurelia-configuration",
  "path": "../node_modules/aurelia-configuration/dist/commonjs",
  "main": "index"
},
"deep-extend"
```
