### ISSUE TITLE
error TS2322: Type 'typeof Configure' is not assignable to type 'Configure'.  

### ISSUE THREAD

**Issue by pete-hotchkiss** [Vheissu/Aurelia-Configuration#66]
I'm getting a TS2322 error when trying to use this plugin.

In my main.ts auerlia config file I have the following 
```
aurelia.use
    .standardConfiguration()
    .developmentLogging()
    .plugin("aurelia-cookie")
    .plugin("aurelia-configuration", config => {
        config.setEnvironments({
            development: ["localhost", "dev.local"],
            testing: ["test.mydomain.com"]
        });
    });
```

In my view model I have the following

```
import { Configure } from "aurelia-configuration";
@autoinject()
export class Home {
constructor() {

    this.config = Configure;
}
```

Initially, when trying to get this up and running I got an error like the below

> Error: app\modules\orders\home\home.ts(2,27): error TS2306: File 'C:/Users/phk/path/to/my/app/node_modules/aurelia-configuration/dist/index.d.ts' is not a module.

I found this - https://github.com/Vheissu/Aurelia-Configuration/issues/57 - and tried making these changes, which evolved the error, to what I currently have:

> error TS2322: Type 'typeof Configure' is not assignable to type 'Configure'. Property 'loader' is missing in type 'typeof Configure'.

I've installed the plugin via jspm and npm but no joy.

**Comment by Vheissu** [comment]
I think your constructor might be the cause. You're missing the argument and you are using TypeScript by the looks of it, so you need to define the class property you're assigning as well.

```
constructor(configure: Configure) {
    this.config = configure;
}
```

**Comment by pete-hotchkiss** [comment]
correct - am using TS, but having the class property in the constructor didn't resolve the issue

I resolved by rolling back to v1.0.4 of the plugin and all working as expected

**Comment by Vheissu** [comment]
No worries @pete-hotchkiss got some fixes coming out shortly.

**Comment by Vheissu** [comment]
I have pushed out release 1.0.13 which should fix this. Please let me know if it doesn't.
