### ISSUE TITLE
Error when installing it through typings

### ISSUE THREAD

**Issue by EduwHS** [Vheissu/Aurelia-Configuration#67]
Hello.
 I'm facing an error trying to install the typings.

First I runned the jspm install:
> jspm install aurelia-configuration

Fore some reason I still need to run typings install for every dependency because the .ts doesn't recognize the imports.
> typings install github:vheissu/aurelia-configuration

But running the typings install returned this error

```bash
 typings WARN badlocation "github:vheissu/aurelia-configuration" is mutable and may change, consider specifying a commit hash
 typings ERR! message Unable to resolve "github:vheissu/aurelia-configuration"
 typings ERR! caused by https://raw.githubusercontent.com/vheissu/aurelia-configuration/master/typings.json responded with 404, expected it to equal 200
```

Does anyone know how to fix this problem? I'm using the aurelia typescript skeleton template.

**Comment by fracz** [comment]
Did you manage to solve it? I am facing the same issue.

**Comment by EduwHS** [comment]
I'm farrelly new to the typescript environment. I still don't know a way to fix this.

**Comment by Freshcutdevelopment** [comment]
You can get this working with `typings install aurelia-configuration=github:vheissu/aurelia-configuration/dist/index.d.ts --global --save`. Just need to include the full path to the index file.

**Comment by fracz** [comment]
But this dependency should not be global, AFAIU...

**Comment by Vheissu** [comment]
The above solution will work for installing through typings. The typings are shipped with the plugin, so in most cases you shouldn't need to do that if you're on the latest version of TypeScript. However, until Jspm implements a solution for typings, the above will work.
