### ISSUE TITLE
ETA to have a new package for the mid-october release?

### ISSUE THREAD

**Issue by Jak3b0** [Vheissu/Aurelia-Configuration#7]
Hi,

I saw that you started working on upgrading your code to support the mid-october Aurelia release. Do you have an ETA as to when the new package will be published?

Also, I must say that your plugin saved me a lot of time.. keep up the good work! :)

**Comment by Vheissu** [comment]
The new package I am planning on getting out in the next week or so. There are some changes in how environment variable stuff works and a few other tweaks that improve the overall API design and fix some shortcomings with configuration loading as well.

These changes will allow both configuration files and URL endpoints for configuration data (so you don't have to commit config files) and also the option to mix both combinations together (partial config file on disk, partially API loaded JSON configuration data).

**Comment by Jak3b0** [comment]
Thanks! :+1:

**Comment by Vheissu** [comment]
Currently working on the new release. Now that beta 1 is out, things are more stable and the new version should be great.
