### ISSUE TITLE
Default config-folder-root moved

### ISSUE THREAD

**Issue by heikomat** [Vheissu/aurelia-configuration#70]
The default config-folder used by aurelia-configuration seems to have moved in 1.0.13. before it was ./src/config, now it's ./config.
When i noticed this, i tried setting the default root, but i found no option that allowed me to set it (i can set the config-folder, but not the root-folder).
My question is: How can i prevent future releases from breaking my config with changes like this one?

**Comment by Vheissu** [comment]
This was poor form on my part introducing a breaking change in a minor release, under much more control now and this hopefully should no longer be an issue.
