### ISSUE TITLE
Typescript d.ts still doesn't work in 1.0.13

### ISSUE THREAD

**Issue by dkent600** [Vheissu/aurelia-configuration#72]
The typings d.ts in v1.0.13 still doesn't define "aurelia-configuration".  It should be named index.d.ts, not aurelia-validation.d.ts.  It is not findable by 'typings', that I am able to accomplish.

**Comment by Vheissu** [comment]
I have pushed a new update, give it a shot.

**Comment by larsn7113** [comment]
I think the typings are supplied using npm but not jspm? (I got it to work by copying  content in typescript-definition.d.ts and put that in a file in a custom_typings folder).

**Comment by dkent600** [comment]
How can one obtain the d.ts?  (I am using typings v2.0.0).  

Thanks.

**Comment by larsn7113** [comment]
https://github.com/Vheissu/aurelia-configuration/blob/master/typescript-definition.d.ts

**Comment by dkent600** [comment]
Thanks, but I am hoping for a means to obtain the d.ts through the standard means using "typings".

**Comment by Vheissu** [comment]
Typings should automatically resolve if you're using TypeScript, for Jspm it is another story though. If you're using `typings` then I believe you can specify files from a Git repository to do so.
