### ISSUE TITLE
Cannot find module 'aurelia-configuration' error

### ISSUE THREAD

**Issue by sholchi** [Vheissu/aurelia-configuration#75]
![cannotfindmoduleaurliaconfiguration](https://cloud.githubusercontent.com/assets/734193/19757326/0e99388c-9c6e-11e6-8711-63e78e9d39f0.jpg)

I am getting this issue with VS 2015 and TypeScript. 

![cannotfindmoduleaurliaconfiguration2](https://cloud.githubusercontent.com/assets/734193/19757373/5169dfc2-9c6e-11e6-8479-d6cebca5f15d.jpg)

**Comment by Vheissu** [comment]
Give this a try now.

**Comment by komenixx** [comment]
In 1.0.14 .d.ts missing

**Comment by Vheissu** [comment]
Closing this as the latest update is working and for Jspm, you can manually map the typings as per the updated readme.
