### ISSUE TITLE
"index.d.ts" missing

### ISSUE THREAD

**Issue by htxryan** [Vheissu/aurelia-configuration#76]
Getting the following error upon installing fresh.

typings ERR! message Unable to read typings for "aurelia-configuration". You should check the entry paths in "index.d.ts" are up to date
typings ERR! caused by https://raw.githubusercontent.com/vheissu/aurelia-configuration/master/dist/index.d.ts responded with 404, expected it to equal 200

It looks like the "index.d.ts" file was removed from the master branch. I do see it in 1.0.11.

**Comment by Vheissu** [comment]
This is fixed in the latest release.
