### ISSUE TITLE
aurelia-configurator.js not found

### ISSUE THREAD

**Issue by comister** [Vheissu/aurelia-configuration#78]
I installed everything with jspm, if I try to do `import {Configure} from 'aurelia-configuration';` it replies with `ENOENT: no such file or directory, open '......../src/aurelia-configuration.js'`so it seems not to find the plugin (for whatever reason). If I am going to add 'aurelia-configuration' to the dependencies in aurelia.json it blames me with `no such file or directory, open 'node_modules/aurelia-configuration/package.json'`, node_modules are done with npm, so after doing `npm install aurelia-configuration --save` a new error comes along stating `ENOENT: no such file or directory, open ......../src/configure.js`
I also added the .use directive into the main.js, so followed the instructions exactly ...
... however, I am not sure what I am missing, any help (maybe update of readme) appreciated.

Thanks

**Comment by comister** [comment]
just fyi, not sure if thats the way to approach this, but I added the following lines to my dependencies in aurelia.json which solved my issue from above, however, the default config location is at /config/config.json , this differs from the readme, not sure if somebody can update that ?

`,
          {
            "name": "deep-extend",
            "path": "../node_modules/deep-extend",
            "main": "index"
          },
          {
            "name": "aurelia-configuration",
            "path": "../node_modules/aurelia-configuration/dist/amd",
            "main": "index",
            "deps": ["deep-extend"]
          }`

**Comment by johnsmith9264** [comment]
I got same error. And fix above solved that. It's interesting what's the reason...

**Comment by Vheissu** [comment]
Latest release addresses this, the README details how to add in support for CLI now as well. The `deep-extend` dependency has also been moved inline.
