### ISSUE TITLE
using in cordova project - loader just stops

### ISSUE THREAD

**Issue by darylcober** [Vheissu/aurelia-configuration#79]
I have an aurelia cli project (works perfect in browser) however when I compile and run in xcode it crashes simulator during the aurelia-configuration plugin initialization. There are no errors logged, it simply stops. At first I was getting a config file not found error but I solved that by changing the directory as follows:

<pre><code>
.plugin('aurelia-configuration', (config) => {  
        config.setDirectory('./config');  
        config.setConfig('config.json');  
    })
</code></pre>

Now I see the config file loading in xcode but it still simply hangs the process.

If I comment the above code my project builds and runs perfectly in xcode.

I really like the way this plugin works, however if I cannot solve this issue in cordova then I simply cannot use it.

**Comment by Vheissu** [comment]
@darylcober Can you please give the latest release a try? Please see the README, there were a couple of small breaking changes (class renamed).

**Comment by brian-g** [comment]
Using 1.0.17 I am running into this problem as well. 

We are initializing the plugin in the configure() function in our main.js. It fails with simply:

`aurelia.use.plugin('aurelia-configuration');`

**Comment by Vheissu** [comment]
Looks like this is an issue I can't see a fix for if it's permissions related. Would loading the JSON file yourself and then passing it into the plugin be a possible solution?
