### ISSUE TITLE
http-client dependency

### ISSUE THREAD

**Issue by CasiOo** [Vheissu/Aurelia-Configuration#8]
It's a shame to have such a great configuration plugin depend on just one http-client implementation.

For our own project, we aren't using Aurelia's http-client at all, and we don't want to include it just for getting this plugin working.

Any way we can inject the .json file ourselves, feed it to the configuration instance, and forget all about the aurelia-http-client :) ?

**Comment by Vheissu** [comment]
I completely agree with you. In-fact, the newer version which I hope to have out very shortly will have no dependency on aurelia-http-client. A much better solution for loading JSON files is coming.

**Comment by chrismbeckett** [comment]
Aurelia is using SystemJS and JSPM. SystemJS provides a built-in ability to load JSON file:

```js
import config from 'lib/config.json!json';
```

or if you want to load dynamically, you can load it on the fly:

```js
System.import('lib/config.json!json');
```

By using SystemJS to import the JSON file, you can also include it with bundling operations.

**Comment by bsrdjan** [comment]
Would you consider adding a [minifier](https://github.com/getify/JSON.minify/tree/javascript), to enable comments in JSON ?
How is going with removing htt-client dep ?

**Comment by Vheissu** [comment]
Removed the Http Client dependency in favour of the Aurelia loader instead.
