### ISSUE TITLE
1.0.15 - "no exported member 'Configure'."?

### ISSUE THREAD

**Issue by don-bluelinegrid** [Vheissu/aurelia-configuration#85]
@Vheissu 

In a project that was previously working fine with aurelia-configuration, upon updating to the latest version 1.0.15, I'm getting webpack/typescript build error messages like this:
```
ERROR in [default] /var/lib/jenkins/workspace/grid-command-v2-dev/src/community-detail.ts:5:8 
Module '"/var/lib/jenkins/workspace/grid-command-v2-dev/node_modules/aurelia-configuration/dist/commonjs/index"' has no exported member 'Configure'.
```

Can you please provide some guidance about changes related to this and migrating a project to this new version?

Thanks,
Don

**Comment by don-bluelinegrid** [comment]
It looks like this:
```
{Configure} from 'aurelia-configuration';
```

was changed to this:
```
{aurelia-configuration} from 'aurelia-configuration';
```

Is this by design, or a typo?  Seems unusual to have the name of the exported type be a hyphenated filename of the containing file.

**Comment by don-bluelinegrid** [comment]
Also, this is causing typescript compilation problems, and problems in VisualStudio Code - it seems hyphenated string literals aren't allowed as import specifiers.

Can this be changed back to a more typical type name?

**Comment by Vheissu** [comment]
@don-bluelinegrid Hi mate, looks like I forgot to push my change to the README which detailed the name change.

Instead of importing `Configure` you now import `AureliaConfiguration` (not hyphenated).

```
import {AureliaConfiguration} from 'aurelia-configuration';
```

**Comment by don-bluelinegrid** [comment]
Right, the ReadMe showed
```
import {aurelia-configuration} from 'aurelia-configuration'
```

**Comment by don-bluelinegrid** [comment]
You may also want to add in the README that this is no longer valid:
```
/// <reference path="../node_modules/aurelia-configuration/typescript-definition.d.ts" />
```
as it appears the type definition has moved, in faovr of:
```
/// <reference path="../node_modules/aurelia-configuration/dist/system/index.d.ts" />
```

**Comment by Vheissu** [comment]
@don-bluelinegrid Curious what build environment you're running; Webpack, CLI or JSPM? I am going to guess JSPM if you're setting the path to the typings. Is that correct?

**Comment by don-bluelinegrid** [comment]
@Vheissu 

Using webpack/typescript.

How would you recommend to set it up so that the typings are found without needing to specify the path?

**Comment by Vheissu** [comment]
You shouldn't need to do anything. Typings should be discovered if you're using a `moduleResolution` value of `node` - do you know what version of TypeScript you're running? As per my `package.json` I am running:

```
"typescript": "2.1.1",
```

And seeing the typings being discovered fine using Webpack/TypeScript.
