### ISSUE TITLE
1.0.15 webpack/typescript breaking build error on Windows OS

### ISSUE THREAD

**Issue by don-bluelinegrid** [Vheissu/aurelia-configuration#86]
When running a webpack/typescript build on a Windows OS system, the webpack build fails with errors related to aurelia-configuration 1.0.15:

```
[default] C:\Users\Pavel\Desktop\grid-command-v2\node_modules\aurelia-configuration\dist\system\index.d.ts:1:40
    Cannot find module 'aurelia-framework'.
[default] C:\Users\Pavel\Desktop\grid-command-v2\node_modules\aurelia-configuration\dist\system\index.d.ts:2:38
    Cannot find module './aurelia-configuration'.
[default] Checking finished with 2 errors
```

Apparently on Windows the imports at the top of ```index.d.ts``` are not being correctly resolved.  I don't have a specific idea of why this would be happening, but we have reproduced the problem on two different Windows OS systems.  Does not matter if an entry exits in custom.d.ts or not.

This did not occur with prior versions of aurelia-configuration, and does not occur with other npm packages.

Is this package supported on Windows OS?

Thanks,
Don

**Comment by Vheissu** [comment]
This should have been resolved in the latest release. Closing it as I could not replicate it with 1.0.17.
