### ISSUE TITLE
Environment checking doesn't do exact checking

### ISSUE THREAD

**Issue by Scrunshes** [Vheissu/aurelia-configuration#87]
Environment checking is using `str.search` which is confusing with what is said in the description and can create problems for some people.
Let's say you have this configuration :
```js
 config.setEnvironments({
        development: ['localhost'],
        bar    : ['foo.localhost']
      });
``` 
`str.search` is gonna be non equal to -1 in both cases, then the first host in the loop partially matching or totally matching will be used. 
I think this is not the intended behavior. I will be happy to provide a patch for this if everyone agrees the intended behavior should be exact matching.

**Comment by Vheissu** [comment]
@Scrunshes I believe you are correct. If you would like to submit a PR, I would love to merge it.

**Comment by Vheissu** [comment]
Thanks @Scrunshes I've merged this, will release today.

**Comment by Scrunshes** [comment]
Perfect :-)
