### ISSUE TITLE
Configuration file could not be found or loaded

### ISSUE THREAD

**Issue by wshayes** [Vheissu/Aurelia-Configuration#9]
I'm getting the error:  Configuration file could not be found or loaded.

I have 'config/application.json' in my root directory.  Same place as I put it in a new install of the skeleton app (Aurelia Beta version) which worked fine.  Not sure what the next steps are for troubleshooting. I've done some debugging but it steps into the shim.js file, and I'm lost at that point.  Any ideas on next steps?  Thanks!

Excerpts from config.js:
    "aurelia-animator-css": "npm:aurelia-animator-css@1.0.0-beta.1.0.1",
    "aurelia-auth": "github:paulvanbladel/aurelia-auth@0.11.3",
    "aurelia-bootstrapper": "npm:aurelia-bootstrapper@1.0.0-beta.1",
    "aurelia-configuration": "github:vheissu/aurelia-configuration@1.0.3",
    "aurelia-fetch-client": "npm:aurelia-fetch-client@1.0.0-beta.1",
    "aurelia-framework": "npm:aurelia-framework@1.0.0-beta.1.0.1",
    "aurelia-history-browser": "npm:aurelia-history-browser@1.0.0-beta.1",
    "aurelia-loader-default": "npm:aurelia-loader-default@1.0.0-beta.1.0.1",
    "aurelia-logging-console": "npm:aurelia-logging-console@1.0.0-beta.1",
    "aurelia-router": "npm:aurelia-router@1.0.0-beta.1",
    "aurelia-templating-binding": "npm:aurelia-templating-binding@1.0.0-beta.1",
    "aurelia-templating-resources": "npm:aurelia-templating-resources@1.0.0-beta.1.0.1",
    "aurelia-templating-router": "npm:aurelia-templating-router@1.0.0-beta.1.0.1",
    "babel": "npm:babel-core@5.8.34",
    "babel-runtime": "npm:babel-runtime@5.8.34",
    "bootstrap": "github:twbs/bootstrap@3.3.5",
    "core-js": "npm:core-js@1.2.6",
    "fetch": "github:github/fetch@0.10.1",
    "font-awesome": "npm:font-awesome@4.4.0",
    "text": "github:systemjs/plugin-text@0.0.3",
...
    "github:vheissu/aurelia-configuration@1.0.3": {
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.9.2",
      "aurelia-event-aggregator": "github:aurelia/event-aggregator@0.7.0",
      "aurelia-http-client": "github:aurelia/http-client@0.10.3",
      "core-js": "npm:core-js@0.9.18"
    },

From Chrome:
Here is the error snapshot:  https://www.evernote.com/l/AAKq1zmclN1BxK2N661HIGo_WUo5FnsJ_PU

**Comment by go4cas** [comment]
@wshayes, did you manage to find a work-around for this issue?

**Comment by wshayes** [comment]
No - I shifted to my own simple config.js for configuration mgmt for the localdev, test, prod servers.
