### ISSUE TITLE
Could you provide a license

### ISSUE THREAD

**Issue by a-jackson** [Vheissu/aurelia-configuration#95]
We would like to use this in our project but there is no license file, as such, we can't.

Can you include a license?

**Comment by AdamWillden** [comment]
I can see you have `"licence": "MIT"` in `package.json` but not sure if that is sufficient...

**Comment by Vheissu** [comment]
@a-jackson @AdamWillden Absolutely guys. I'll add one in now, my bad.

**Comment by AdamWillden** [comment]
nice once @Vheissu :-)

**Comment by a-jackson** [comment]
Perfect, thanks
