### ISSUE TITLE
Change setEnvironments to also handle window.location.pathname and not just hostname:port

### ISSUE THREAD

**Issue by omniscient** [Vheissu/aurelia-configuration#98]
When deploying multiple versions of the same application on the same domain, the configuration doesn't work. I am willing to make this change but wondering if you are willing to merge it or not.

Basically, I have a need to be able to do this:

```
config.setEnvironments({
        local: ['localhost:9000'],
        localWeb: ['localhost'],
        devMaster: ['apps.mydomain.com/test/master/ui'],
        devProd: ['apps.mydomain.com/test/prod/ui'],
        devbranchx: ['apps.mydomain.com/test/branchx/ui']
      });
```
Let me know if you agree with this approach and you are willing to merge if I PR it.

**Comment by weaverj** [comment]
Same need here, basically ability would be able to include port number in the matching, not just the domain name.  In general, it would also help to have the documentation for this plugin be much more specific about how this matching takes place - what parts of the URL are considered when matching.

**Comment by omniscient** [comment]
This ticket can be closed now
